[INFO    :             django.server] - 2024-02-20 13:25:11,974 : log_message @ 0212: "GET /judges/participants_list/ HTTP/1.1" 200 13217
[INFO    :             django.server] - 2024-02-20 13:25:13,845 : log_message @ 0212: "GET /judges/add_participant HTTP/1.1" 200 13242
[INFO    :      app_for_judges.views] - 2024-02-20 13:25:40,165 : add_participant @ 0169: Participant Перикл Оренбургский added
[INFO    :             django.server] - 2024-02-20 13:25:40,176 : log_message @ 0212: "POST /judges/add_participant HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-02-20 13:25:40,212 : log_message @ 0212: "GET /judges/participants_list/ HTTP/1.1" 200 13592
[INFO    :             django.server] - 2024-02-20 13:25:57,456 : log_message @ 0212: "GET /competitions/all/ HTTP/1.1" 200 17117
[INFO    :             django.server] - 2024-02-20 13:25:58,488 : log_message @ 0212: "GET /competitions/view_competition/1/ HTTP/1.1" 200 12742
[INFO    :             django.server] - 2024-02-20 13:26:02,265 : log_message @ 0212: "GET /competitions/judge_task/1/1/ HTTP/1.1" 200 14352
[INFO    :             django.server] - 2024-02-20 13:26:03,824 : log_message @ 0212: "GET /judges/add_participant HTTP/1.1" 200 13242
[ERROR   :            django.request] - 2024-02-20 13:26:18,843 : log_response @ 0241: Internal Server Error: /competitions/judge_task/1/1/
Traceback (most recent call last):
  File "C:\Users\Александр\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Александр\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Александр\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view app_for_competitions.views.judge_task didn't return an HttpResponse object. It returned None instead.
[ERROR   :             django.server] - 2024-02-20 13:26:18,857 : log_message @ 0212: "POST /competitions/judge_task/1/1/ HTTP/1.1" 500 81322
